# Generated by Django 3.2.5 on 2021-08-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Admission Batch'),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=1, verbose_name='Year'),
        ),
    ]
