# Generated by Django 3.2.5 on 2021-08-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210816_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Student slug'),
        ),
    ]
